// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniConnect_Projeto.Data;

#nullable disable

namespace UniConnect_Projeto.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251123234629_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniConnect_Projeto.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("Coordenador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CursosTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("DisciplinaTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.GrupoEstudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublico")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("GrupoEstudoTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.GrupoEstudoAluno", b =>
                {
                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntrouEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsModerador")
                        .HasColumnType("bit");

                    b.HasKey("GrupoId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("GrupoEstudoAlunoTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("TurmaId");

                    b.ToTable("MaterialTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.MaterialLike", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MaterialId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("MaterialLikeTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.RecomendacaoEstudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("RecomendacaoTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Termo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso");

                    b.ToTable("TurmaTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.TurmaAluno", b =>
                {
                    b.Property<int>("IdTurma")
                        .HasColumnType("int");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.HasKey("IdTurma", "IdAluno");

                    b.HasIndex("IdAluno");

                    b.ToTable("TurmaAlunoTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.TurmaProfessor", b =>
                {
                    b.Property<int>("IdTurma")
                        .HasColumnType("int");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("int");

                    b.HasKey("IdTurma", "IdProfessor");

                    b.HasIndex("IdProfessor");

                    b.ToTable("TurmaProfessorTable");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsuariosTable");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Admin", b =>
                {
                    b.HasBaseType("UniConnect_Projeto.Models.Usuario");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Aluno", b =>
                {
                    b.HasBaseType("UniConnect_Projeto.Models.Usuario");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.HasIndex("CursoId");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Professor", b =>
                {
                    b.HasBaseType("UniConnect_Projeto.Models.Usuario");

                    b.HasDiscriminator().HasValue("Professor");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Disciplina", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.GrupoEstudo", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Aluno", "Criador")
                        .WithMany("GruposCriados")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect_Projeto.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Criador");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.GrupoEstudoAluno", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Aluno", "Aluno")
                        .WithMany("Grupos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect_Projeto.Models.GrupoEstudo", "Grupo")
                        .WithMany("Membros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Material", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Aluno", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect_Projeto.Models.GrupoEstudo", "Grupo")
                        .WithMany("Materiais")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniConnect_Projeto.Models.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Autor");

                    b.Navigation("Grupo");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.MaterialLike", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Aluno", "Aluno")
                        .WithMany("MaterialLikes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect_Projeto.Models.Material", "Material")
                        .WithMany("LikesBy")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.RecomendacaoEstudo", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Aluno", "Aluno")
                        .WithMany("Recomendacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Turma", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Curso", "Curso")
                        .WithMany("Turmas")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.TurmaAluno", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Aluno", "Aluno")
                        .WithMany("Turmas")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect_Projeto.Models.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.TurmaProfessor", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Professor", "Professor")
                        .WithMany("Turmas")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect_Projeto.Models.Turma", "Turma")
                        .WithMany("Professores")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Aluno", b =>
                {
                    b.HasOne("UniConnect_Projeto.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Curso", b =>
                {
                    b.Navigation("Disciplinas");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.GrupoEstudo", b =>
                {
                    b.Navigation("Materiais");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Material", b =>
                {
                    b.Navigation("LikesBy");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Turma", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Professores");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Aluno", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("GruposCriados");

                    b.Navigation("MaterialLikes");

                    b.Navigation("Recomendacoes");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("UniConnect_Projeto.Models.Professor", b =>
                {
                    b.Navigation("Turmas");
                });
#pragma warning restore 612, 618
        }
    }
}
